package common

const(

	EVENT_TYPE_SIMPLE_SEND = 0
	EVENT_TYPE_BUY_CROWD_TOKEN = 1
	EVENT_TYPE_AIR_DROP = 3
	EVENT_TYPE_SEND_ALL = 4
	EVENT_TYPE_CREATE_FIXED_TOKEN = 50
	EVENT_TYPE_CREATE_CROWD_TOKEN = 51
	EVENT_TYPE_CREATE_MANAGE_TOKEN = 54
	EVENT_TYPE_CLOSE_CROWD_TOKEN = 53
	EVENT_TYPE_GRANT_TOKEN = 55
	EVENT_TYPE_REVOKE_TOKEN = 56
	EVENT_TYPE_BURN_BCH = 68
	EVENT_TYPE_CHANGE_TOKEN_ISSUER = 70

)
